### ISSUE TITLE
Possible conflict with Character Editor resulting in "baby sleeves"

### ISSUE THREAD

**Issue by klassekatze** [Helixien/AlteredCarbon#2]
Went to clone up a sleeve, and all I got were babies in the preview. Accepting anyway had the clone aging _negatively_.

More frustratingly, it didn't happen in other playthroughs... except if I'd loaded this one. After loading this save, the bug manifested in other loaded saves during the session even if they did not previously exhibit the problem. Conversely, loading a test map only didn't reliably cause it.

Repro:

[Atkahisera_TEST_min.zip](https://github.com/Helixien/AlteredCarbon/files/10415985/Atkahisera_TEST_min.zip)

Loading Atkahisera_TEST_min with  Character Editor active, target any pawn for cloning, observe baby in preview. Confirm clone, have a pawn set it going, observe _negative aging_ of the clone, as in it becomes younger than zero though never more than -24 hours. Debug: instant grow produces a "finished" negative age clone.
 
Loading the same savefile with Character Editor removed from the mod list results in expected, normal cloning.

**Comment by Taranchuk** [comment]
Should be solved now
