### ISSUE TITLE
[Bug]: The job "Duplicate stack" seems to use the wrong skill value

### ISSUE THREAD

**Issue by Ronkhar** [Helixien/AlteredCarbon#4]
Hi,
The job "Duplicate stack" says "requires intellectual of 10 or higher".
Currently, the check compares 10 to the value of "learned level" instead of "Skill level", which creates issues for pawns with an intellectual genetic offset.
**Example of a genie pawn:** learned level@9 + great intellectual xenogene@8  ==> skill level@17
**Problem**: The pawn is unable to duplicate stacks.
If learned level increases at 10, the pawn can duplicate stacks.

From multiple tests and a little bit of code reading, It looks like the same function is used when checking if the duplication is a success. (a genie with intel 12+8 has the success rate of a pawn with intel 12, not a pawn with intel 20)

StackGroupData.cs line 218
`float successChance = 1f - Mathf.Abs((doer.skills.GetSkill(SkillDefOf.Intellectual).levelInt / 2f) - 11f) / 10f;`
WorkGiver_DuplicateStacks.cs, line 22
`if (pawn.skills.GetSkill(SkillDefOf.Intellectual).levelInt < 10)`

**Comment by Taranchuk** [comment]
Fixed now, thanks for the report
