### ISSUE TITLE
New colonist when removing an empty cortical stack from sleeve

### ISSUE THREAD

**Issue by bocian67** [Helixien/AlteredCarbon#7]
After removing an empty cortical stack, which was inserted into a fresh sleeve, the cortical stack has a new colonist with (seemingly random) stats and name. 

How to reproduce?
Remove a grown sleeve from the sleeve incubator, and implant an empty cortical stack into the sleeve. After that, remove the cortical stack from the sleeve.

Expected behavior:
The cortical stack is empty, since the sleeve was not alive and the cortical stack was empty. 

Current behavior:
The cortical stack has a bio with name, passions and stats.

Rimworld version: 1.4.3704
Altered Carbon Version: 4.3-ortega-rev4 (probably, latest on steam)

**Comment by Taranchuk** [comment]
Fixed now
