### ISSUE TITLE
Bio of char did not really fit well with the corpse I was looking at. 

### ISSUE THREAD

**Issue by NyarlathotepZERO** [Helixien/AlteredCarbon#8]
NPC spawned on map which had the 'Digital Upbringing' trait, and whilst I realize that traits are probably quite random in their nature, it was unfortunate to see that the 'sleeve' was not fitted with a stack as was hinted at in its bio.

Is there a way to ensure that all 'digital upbringing' NPC's are fitted with stacks ?

**Comment by Taranchuk** [comment]
Fixed now
