### ISSUE TITLE
Harvested stack carried on a perk which I'd assume to be purely physical 

### ISSUE THREAD

**Issue by NyarlathotepZERO** [Helixien/AlteredCarbon#9]
Cortical stacks seem to carry the Impid 'fire spew' perk. I would assume fire spew is more of a feature that is based on physical features rather than something carried and passed on through a cortical stack. 

This stack was harvested off a corpse and therefore probably passed the perk on this way. My suggestion (if it's possible) would be to remove the perk from the stack as soon as it is harvested.

![image](https://github.com/Helixien/AlteredCarbon/assets/26475624/77ccea36-0310-4e17-9b3a-6d868fcfb9b0)

**Comment by Helixien** [comment]
Was fixed a while ago it seems.
